# Copyright (c) 2018, ARM Limited.
# SPDX-License-Identifier: Apache-2.0

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
# specify the cross compiler
set(CMAKE_C_COMPILER $ENV{CROSS_COMPILE}gcc)
set(CMAKE_CXX_COMPILER $ENV{CROSS_COMPILE}g++)
set(ROS_DISTRO humble)
if(DEFINED ENV{ROS_DISTRO})
    set(ROS_DISTRO $ENV{ROS_DISTRO})
endif()
# where is the target environment
set(CMAKE_FIND_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR}/../install ${CMAKE_CURRENT_LIST_DIR}/../build /opt/ros/${ROS_DISTRO} ${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_CROSSCOMPILING_EMULATOR qemu-aarch64-static)
set(CMAKE_SYSROOT ${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker)
set(Qt5Core_DIR ${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker/usr/lib/aarch64-linux-gnu/cmake/Qt5Core)
set(Qt5OpenGL_DIR ${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker/usr/lib/aarch64-linux-gnu/cmake/Qt5OpenGL)
set(Qt5Widgets_DIR ${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker/usr/lib/aarch64-linux-gnu/cmake/Qt5Widgets)
set(Qt5Gui_DIR ${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker/usr/lib/aarch64-linux-gnu/cmake/Qt5Gui)
set(Qt5Test_DIR ${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker/usr/lib/aarch64-linux-gnu/cmake/Qt5Test)
set(Qt5Concurrent_DIR ${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker/usr/lib/aarch64-linux-gnu/cmake/Qt5Concurrent)
set(X11_Xrandr_LIB ${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker/usr/lib/aarch64-linux-gnu/libXrandr.so.2)
set(X11_Xaw_LIB    ${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker/usr/lib/aarch64-linux-gnu/libXaw.so)
#set(Python3_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker/usr/")
#set(Python3_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker/usr/include/python3.12")
set(Python3_ROOT_DIR "/usr/")
set(Python3_INCLUDE_DIRS "/usr/include/python3.12/")
set(Python3_NumPy_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker/usr/local/lib/python3.12/dist-packages/numpy/_core/include/numpy")
#set(Python3_NumPy_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../sysroot_docker/usr/lib/python3/dist-packages/numpy/core/include/numpy/")
set(BUILD_TESTING off)
set(BUILD_HBMEM ON)
if("${ROS_DISTRO}" STREQUAL "humble")
    set(PYTHON_SOABI cpython-310-aarch64-linux-gnu)
elseif("${ROS_DISTRO}" STREQUAL "jazzy")
    set(PYTHON_SOABI cpython-312-aarch64-linux-gnu)
endif()
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-rpath-link=/opt/ros/${ROS_DISTRO}/lib/aarch64-linux-gnu")
# This assumes that pthread will be available on the target system
# (this emulates that the return of the TRY_RUN is a return code "0"
set(THREADS_PTHREAD_ARG "0"
  CACHE STRING "Result from TRY_RUN" FORCE)
